### PR TITLE
Refactor into oci.rs and introduce some error handling. 

### PR DESCRIPTION
**Pull request by lukehinds**
Refactor pull to OCI and Error handling
    
To help keep main.rs lean, refactored the pull operation to oci.rs and introduce some error handling to trim down on the unwraps

### CODE REVIEW

**Review by lkatalin — APPROVED** [review]
LGTM, thanks @lukehinds !
Looks like it needs a rebase.

**Review by asraa — APPROVED** [review]

**Comment by imjasonh** [comment]
Might also be worth consolidating on https://github.com/krustlet/oci-distribution, or some other OCI Rust library that both could use.

**Comment by lukehinds** [comment]
> Might also be worth consolidating on https://github.com/krustlet/oci-distribution, or some other OCI Rust library that both could use.

That's actually the very one we are using.

**Comment by imjasonh** [comment]
> That's actually the very one we are using.

Oh whoops, I need to read better! 😅

**Pull request merged**
