### PR TITLE
Fix CI: workflow can't specify both uses: and run:

### PR DESCRIPTION
**Pull request by imjasonh**
#### Summary

CI runs have been failing: https://github.com/sigstore/sget/actions/workflows/main.yml

Example taken from https://github.com/actions-rs/clippy-check#with-stable-clippy

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by lukehinds — APPROVED** [review]

**Comment by lukehinds** [comment]
a couple of failures @imjasonh , not sure the root cause yet.

**Comment by lkatalin** [comment]
@imjasonh I know there's a lot going on here... I can fix the banned functions in main().

**Comment by lkatalin** [comment]
I'm not sure what's going on with the Windows error, however... looks like it may be a PATH issue?

**Comment by lkatalin** [comment]
Looks like it's related to this https://stackoverflow.com/questions/63151602/rust-process-failed-with-exit-code-101-using-github-actions

**Comment by imjasonh** [comment]
> I'm not sure what's going on with the Windows error, however... looks like it may be a PATH issue?

I'm not sure what's up with that either. I'd be fine disabling Windows (and macOS?) for now to unblock CI on Linux. Some CI is better than none 😆

**Comment by lkatalin** [comment]
> > I'm not sure what's going on with the Windows error, however... looks like it may be a PATH issue?
> 
> I'm not sure what's up with that either. I'd be fine disabling Windows (and macOS?) for now to unblock CI on Linux. Some CI is better than none laughing

Yeah, I am making an attempt to figure out what's wrong with it but otherwise I agree.

**Comment by imjasonh** [comment]
Thanks for merging! Now that CI works, a repo admin can make a passing CI check a requirement for merging future PRs, which should prevent regressions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

**Comment by lkatalin** [comment]
> Thanks for merging! Now that CI works, a repo admin can make a passing CI check a requirement for merging future PRs, which should prevent regressions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

@imjasonh We should definitely do this. It appears to require creating branch protection rules in some way, which I don't know enough about to do right now, so I'm creating an issue.

**Comment by lukehinds** [comment]
@lkatalin / @imjasonh is this all actions?

image

**Comment by imjasonh** [comment]
> @lkatalin / @imjasonh is this all actions?

I'm not sure what `clippy` is, only the other four were run on a recent PR: https://github.com/sigstore/sget/actions/runs/1517385859

**Comment by lkatalin** [comment]
Clippy is basically the Rust linter. I think we should require clippy as well. I'm just not very familiar with the GitHub Actions interface to make that happen.

**Pull request merged**
