### PR TITLE
Don't exec by default, print to stdout unless --outfile

### LINKED ISSUE #46: Consider dropping script execution
**Description**

I think we should consider dropping script execution, or at least make it off by default.  curl | bash still requires bash :)

Executing a binary directly seems a bit scary. I can see running a script in a shell, but would we want to run anything?

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes #46 

#### Summary

This PR changes `sget`'s default behavior:
- without flags, `sget` will fetch the contents and print them to stdout
- `--exec` will write the contents to `--outfile` and execute it
- `--outfile` will write the contents to an outfile

This is the first "real" Rust I've ever written. Please be gentle, but also please don't let me get away with anything stupid 😆

Demo:
```
$ echo "echo hello" > test.sh
$ img=$(cosign upload blob -f test.sh gcr.io/imjasonh/test)                                                                                                                                                                                    
$ echo $img
gcr.io/imjasonh/test@sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622
$ cargo run $img
...rust stuff
echo hello
$ cargo run $img | sh
...rust stuff
hello
```

#### Release Note

```release-note
sget prints fetched contents to stdout by default
```

@jyotsna-penumaka @lukehinds

### CODE REVIEW

**Comment by imjasonh** [comment]
I'm going to give up on the e2e test for now, `sget` seems to not like fetching from a local registry over http. We can fix that in a future change.

**Comment by imjasonh** [comment]
Copying from Slack for posterity:

> It's possible that exec has been subtly broken. Currently we don't make the file executable before executing it, we usually seem to just overwrite tests/test.sh in the repo, which is already executable. But in my PR I'm trying to write to a tempfile when --execing, and chmoding that tempfile fails on Windows. It seems there's a lot I don't know about Windows permissions, maybe "making something executable" is a meaningless thing in Windows and we should just skip it there. In any case, I'd also like to get better e2e tests to cover all our bases, but that'll have to be next week.

This PR should fix this issue (~~or if Windows continues to be a pain I may give up and add a TODO~~ got it yayyy 🎉 ), but this does point to the need for better e2e test coverage.

edit: Oh, I see, previously `--exec` was intended to be used with `--outfile`. In this change, I'm currently ignoring `outfile` if `exec` is set, but I suppose we could also use `outfile` instead of always writing a tempfile.

**Comment by jyotsna-penumaka** [comment]
@imjasonh 
It looks good to me :1st_place_medal: 
The only part I am not sure about is, the creation of a temporary file when the user decides to execute the script.
Ideally we would want to keep the dependency list as thin as possible, but the creation of a temporary file is adding another dependency to the list.

**Comment by imjasonh** [comment]
Totally reasonable. I'd be willing to go back to `--exec` requiring an `--outfile` like we require today, that'd be fine.

**Comment by imjasonh** [comment]
> Totally reasonable. I'd be willing to go back to `--exec` requiring an `--outfile` like we require today, that'd be fine.

Wow, this is a lot better!

For some reason I'm still getting a `Permission denied` error when I try:

```
$ cargo run $img --outfile=newfile.sh --exec
thread 'main' panicked at 'Execution failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:65:60
```

This works on `main` however:

```
$ cargo run $img --outfile=newfile.sh
Successfully retrieved file
Hello Sigstore!
sget execution succeeded
```

~~Not sure what I'm missing... I'll keep looking.~~

Oh! I got it. On `main`, when `cargo run $img --outfile=newfile.sh`, it would fetch and write `newfile.sh`, _then_ always execute `$CARGO_MANIFEST_DIR/tests/test.sh`, which happens to be `tests/test.sh` in our repo, which exists and is executable. If I delete that file, `cargo run $img --outfile=newfile.sh` fails. So `exec`-mode seems to have been broken before this change.

I think we need to make `outfile` executable before running it, and probably have a better e2e test that writes a new file, `cosign upload-blob`s it, and `sget`-fetches and runs it.

edit: _Or_, we could drop `outfile` and `exec`, _always_ just print to stdout, and drop a bunch of code from the codebase. Users who want to write a file can `sget $img > outfile.sh`, and users who want to execute can `sget $img | sh`.

**Comment by jyotsna-penumaka** [comment]
This looks great!
I think we should have the outfile and exec option for now.

I was trying to test the code locally, I was following the demo commands, but I seem to run into an error.
@lkatalin and I were trying to get past the error.

```
$ img=$(cosign upload blob -f test.sh ghcr.io/jyotsna-penumaka/test)
Uploading file from [test.sh] to [ghcr.io/jyotsna-penumaka/test:latest] with media type [text/plain]
File [test.sh] is available directly at [ghcr.io/v2/jyotsna-penumaka/test/blobs/sha256:5dbad7dd0b9b122dcd9956884390f4aac4738caba8ff53498a7ab6718b176c30]
Uploaded image to:

$ echo $img
ghcr.io/jyotsna-penumaka/test@sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622

$ cargo run $img
Compiling sget v0.1.0 (/home/jpenumak/fall_2021/sget)
Finished dev [unoptimized + debuginfo] target(s) in 5.03s
Running `target/debug/sget 'ghcr.io/jyotsna-penumaka/test@sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622'`
Error: OCI API error: authentication required on https://ghcr.io/v2/jyotsna-penumaka/test/manifests/sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622
```
I uploaded it to GitHub and not google's container registry, not sure if this has something to do with the error.
I even made the GitHub package public, not sure why there is an authentication error.

**Comment by imjasonh** [comment]
Do you get that error before this change? I didn't change anything about auth, which seems to always be configured to be `Anonymous`: https://github.com/sigstore/sget/blob/323866284a55c1d21b560dbac8e899f08d330bb6/src/oci.rs#L16

~~You can make the image public at https://github.com/users/jyotsna-penumaka/packages/container/package/test/settings (I think), which should make this work using anonymous credentials in `sget`. But this should exhibit the same behavior before this change, as far as I know.~~

edit: I see, the image is already public (`crane digest $img` works for me). Hmm, I'm not sure why this would happen... 🤔 

FWIW, I still get the authentication error when trying to fetch using `main`:

```
$ [main] cargo run $img --outfile=newfile.sh --noexec
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/sget 'ghcr.io/jyotsna-penumaka/test@sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622' --outfile=newfile.sh --noexec`
File retrieval failed: OCI API error: authentication required on https://ghcr.io/v2/jyotsna-penumaka/test/manifests/sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622
```

**Comment by jyotsna-penumaka** [comment]
I was running into this error before your last change as well.
I tried creating a new token, but that didn't help either.

**Comment by imjasonh** [comment]
> I was running into this error before your last change as well. I tried creating a new token, but that didn't help either.

Yeah I'm inclined to believe this isn't new behavior, but it is something we should investigate further. I think GHCR might somehow have different auth that's incompatible with `oci-distribution`'s `Anonymous`?

In the meantime, I have a public GCR repo you can use to test:

```
$ img=$(cosign upload blob -f tests/test.sh gcr.io/imjasonh/test)
Uploading file from [tests/test.sh] to [gcr.io/imjasonh/test:latest] with media type [text/plain]
File [tests/test.sh] is available directly at [gcr.io/v2/imjasonh/test/blobs/sha256:1724ec942da76bd3c2ef82b5dcc54ba0a5ddbf394c4b637078256366945655de]
Uploaded image to:
$ echo $img
gcr.io/imjasonh/test@sha256:c99359ba4b63a7523525471f82a27fcc887ca2e03ecf6d5847130b2146853c12
$ cargo run $img
   Compiling sget v0.1.0 (/Users/jasonhall/git/sget)
    Finished dev [unoptimized + debuginfo] target(s) in 13.74s
     Running `target/debug/sget 'gcr.io/imjasonh/test@sha256:c99359ba4b63a7523525471f82a27fcc887ca2e03ecf6d5847130b2146853c12'`
#!/bin/bash

echo -n "Hello Sigstore!"

```

**Comment by imjasonh** [comment]
Filed https://github.com/krustlet/oci-distribution/issues/14 to hopefully understand the ghcr.io behavior better.

@jyotsna-penumaka In the meantime, do you have any more comments about this change?

**Comment by jyotsna-penumaka** [comment]
@imjasonh 
I tried using your public GCR repo, but I don't think I have the correct permission to access it.
Thanks for filing the issue :) 
```
$ img=$(cosign upload blob -f tests/test.sh gcr.io/imjasonh/test)
Uploading file from [tests/test.sh] to [gcr.io/imjasonh/test:latest] with media type [text/plain]
error: GET https://gcr.io/v2/token?scope=repository%3Aimjasonh%2Ftest%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by imjasonh** [comment]
> @imjasonh I tried using your public GCR repo, but I don't think I have the correct permission to access it.
> 
> ```
> $ img=$(cosign upload blob -f tests/test.sh gcr.io/imjasonh/test)
> Uploading file from [tests/test.sh] to [gcr.io/imjasonh/test:latest] with media type [text/plain]
> error: GET https://gcr.io/v2/token?scope=repository%3Aimjasonh%2Ftest%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
> ```

That's just telling you you don't have permission to push to my GCR repo (which you don't 😄). You can skip that step and just use the image I've already pushed:

```
img=gcr.io/imjasonh/test@sha256:cdcab0563d63cc1f1dee972d685a1d21b8fef98b11c59ce28803f77e6e93a622
cargo run $img
```

**Comment by jyotsna-penumaka** [comment]
@imjasonh 
Oh that's amazing!
It worked!
Thank you!

**Review by jyotsna-penumaka — APPROVED** [review]

**Pull request merged**
