### PR TITLE
Add justfile

### LINKED ISSUE #19: use just for make
may as well keep it native

https://github.com/casey/just

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes #19

Signed-off-by: Furkan <furkan.turkal@trendyol.com>

#### Summary
```justfile
$ just --list
Available recipes:
    build
    check
    clippy
    default
    fmt
    run
    test

$ just
cargo check --all-features
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
cargo build --release
    Finished release [optimized] target(s) in 0.11s
cargo test .
    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running unittests (target/debug/deps/sget-6731ac87b4456636)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

cargo clippy --all-targets --all-features -- -D clippy::all
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
cargo fmt --all -- --check
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/sget`
```

#### Ticket Link

Fixes #19

#### Release Note

```release-note
* use justfile as make
```

### CODE REVIEW

**Review by lukehinds — APPROVED** [review]
It's a neat tool huh? :)

**Comment by Dentrax** [comment]
Hey @casey, 👋 

This is my first yet `justfile`, works like a charm! I loved it! ❤️

**Comment by casey** [comment]
> This is my first yet `justfile`, works like a charm! I loved it! ❤️

Nice! So glad to hear it. Seeing people add justfiles to their project still makes me super happy, even though I've been working on `just` for a long time.

**Comment by casey** [comment]
One tip, you can do this:

```
default:
    @just test
    @just clippy
    @just fmt
    @just run
```

With dependencies:

```
default: test clippy fmt run
```

If dependencies can be run in the order you give them, they will be, so it will run test first, etc.

**Comment by Dentrax** [comment]
That's cooler! I was copied that `defaut` syntax from [here](https://github.com/casey/just#selecting-recipes-to-run-with-an-interactive-chooser). Maybe we can add detail about the _with dependencies_ example for the `default` model in the [README](https://github.com/casey/just/blob/master/README.adoc)? 🤗

**Comment by casey** [comment]
@Dentrax Good idea, I added a section with different ideas for how to use the default recipe: https://github.com/casey/just/pull/1006

**Pull request merged**
