### PR TITLE
Verify fulcio cert chain

### PR DESCRIPTION
**Pull request by jyotsna-penumaka**
Signed-off-by: jyotsna-penumaka <jpenumak@redhat.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by lukehinds** [comment]
Do you need an example client pem to test with? If so let me know and I can grab one for you.

**Comment by jyotsna-penumaka** [comment]
@lukehinds I am using the client cert that is enclosed inside root.json after I signed the root.
I am verifying that with the fulcio root.
Are you refering to something else?

**Comment by jyotsna-penumaka** [comment]
@Dentrax The CI / Rust project (windows-latest) seems to be failing, and I can't figure out why.
Can you please take a look at it, when you get a chance?

**Review by lukehinds — APPROVED** [review]
This looks good to me, I think we can merge once CI is fixed up.

**Comment by lukehinds** [comment]
> @lukehinds I am using the client cert that is enclosed inside root.json after I signed the root. I am verifying that with the fulcio root. Are you refering to something else?

I see it now, ignore me :)

**Comment by lukehinds** [comment]
I think the CI failure is from a lack of openssl. I am pretty sure the rust implementation is a wrapper around the OS included openssl. I think I know how to fix this, will make a PR

**Comment by lkatalin** [comment]
@lukehinds The CI is still complaining I think because `OPENSSL_DIR` is unset. I've tried to set it to some plausible values but am not sure what it is supposed to be on Windows as I don't have any experience running tests on Windows. Do you have any ideas on what this is supposed to be?

**Comment by lkatalin** [comment]
@jyotsna-penumaka @lukehinds After #56 is merged, if this is rebased on that, I think the CI should work!

**Review by lukehinds — APPROVED** [review]

**Pull request merged**
